# Production: container-compose.yml
services:
  app:
    container_name: people_count
    build:
      context: ./
    image: people_count-dev
    ports:
    - "5041:5041"
    privileged: true
    environment:
    - PYTHONUNBUFFERED=1
    devices:
    - dev/video0
    volumes:
    - $PWD:/app
    restart: always
